// Generated by CoffeeScript 1.8.0

$("#expand").click(function() {
  console.log("this should output something")
  $(".chatroom").slideDown("slow", function () {
  });
  $(".uservideos").slideDown("slow", function () {
  });
  $(".usersBoxContainer").slideDown("slow", function () {
  });
})